ALL_FEATURES= ['age', 'sex', 'Vital_Signs HR', 'Vital_Signs RR', 'Vital_Signs SBP', 'Vital_Signs TEMP',
                   'Vital_Signs SPO2', 'Vital_Signs FiO2', 'Vital_Signs masktyp', 'Vital_Signs avpu',
                   'Blood_Test ALT-IU/L', 'Blood_Test CRP-mg/L', 'Blood_Test Albumin-g/L', 'Blood_Test Urea-mmol/L',
                   'Blood_Test Sodium-mmol/L', 'Blood_Test Haematocrit-L/L', 'Blood_Test Haemoglobin-g/dL',
                   'Blood_Test Bilirubin-umol/L', 'Blood_Test Potassium-mmol/L', 'Blood_Test Basophils-x10^9/L',
                   'Blood_Test Creatinine-umol/L', 'Blood_Test MeanCellVol-fL', 'Blood_Test Monocytes-x10^9/L',
                   'Blood_Test Platelets-x10^9/L', 'Blood_Test Eosinophils-x10^9/L', 'Blood_Test Lymphocytes-x10^9/L',
                   'Blood_Test Neutrophils-x10^9/L', 'Blood_Test WhiteCells-x10^9/L', 'Blood_Test Alk.Phosphatase-IU/L',
                   'Blood_Gas BE ACT (BG)', 'Blood_Gas BE STD (BG)', 'Blood_Gas BICARB (BG)', 'Blood_Gas CA+ + (BG)',
                   'Blood_Gas CL- (BG)', 'Blood_Gas CLAC (BG)', 'Blood_Gas CREAT (BG)', 'Blood_Gas CTO2C (BG)',
                   'Blood_Gas ESTIMATED OSMOLALITY (BG)', 'Blood_Gas FCOHB (BG)', 'Blood_Gas FHHB (BG))',
                   'Blood_Gas FIO2', 'Blood_Gas GLUCOSE (BG)', 'Blood_Gas HB (BG)', 'Blood_Gas HCT (BG)',
                   'Blood_Gas K+ (BG)', 'Blood_Gas METHB (BG)', 'Blood_Gas NA+ (BG)', 'Blood_Gas O2 SAT (BG)',
                   'Blood_Gas P5OC (BG)', 'Blood_Gas PCO2 POC', 'Blood_Gas PH (BG)', 'Blood_Gas PO2 (BG)',
                   'Blood_Gas TEMPERATURE POCT', 'Var_Mean_Vital_Signs HR', 'Max_Min_Vital_Signs HR',
                   'Delta_Mean_Vital_Signs HR', 'Var_Mean_Vital_Signs RR', 'Max_Min_Vital_Signs RR',
                   'Delta_Mean_Vital_Signs RR', 'Var_Mean_Vital_Signs SBP', 'Max_Min_Vital_Signs SBP',
                   'Delta_Mean_Vital_Signs SBP', 'Var_Mean_Vital_Signs TEMP', 'Max_Min_Vital_Signs TEMP',
                   'Delta_Mean_Vital_Signs TEMP', 'Var_Mean_Vital_Signs SPO2', 'Max_Min_Vital_Signs SPO2',
                   'Delta_Mean_Vital_Signs SPO2', 'Var_Mean_Vital_Signs FiO2', 'Max_Min_Vital_Signs FiO2',
                   'Delta_Mean_Vital_Signs FiO2', 'Var_Mean_Vital_Signs masktyp', 'Max_Min_Vital_Signs masktyp',
                   'Delta_Mean_Vital_Signs masktyp', 'Var_Mean_Vital_Signs avpu', 'Max_Min_Vital_Signs avpu',
                   'Delta_Mean_Vital_Signs avpu']