BIN_CLASSIFICATION_WEIGHTS = {0: 1, 1: 1}
#MLP_BIN_CLASSIFICATION_WEIGHTS = {0: 1, 1: 100}

XGBOOST_EVAL_METRIC = 'logloss'

MLP_EVAL_METRIC = 'logloss'
MLP_N_EPOCHS = 50
MLP_PATIENCE = 15
MLP_BATCH_SIZE = 512
MLP_LR = 1e-4 #1e-2

TABNET_EVAL_METRIC = ['logloss']
TAB_NET_EPOCHS = 5
TABNET_BATCH_SIZE = 1024
